# -*- coding: utf-8 -*-
"""TF-IDF Base_Train2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWQzQ9KpoVIEjVPEP4Gqh8qlCqeGHOjL
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np

# Chargement — adapte le chemin si besoin
df = pd.read_csv('Base_Train2.csv')

X = df['Texte']
y_type = df['Types']
y_cat = df['Categories'].fillna('Non Haineux')

# TF-IDF
vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    max_features=5000,
    ngram_range=(1, 2)
)
X_tfidf = vectorizer.fit_transform(X)

# Split 80/20
X_train, X_test, y_train_type, y_test_type, y_train_cat, y_test_cat = train_test_split(
    X_tfidf, y_type, y_cat, test_size=0.2, random_state=42, stratify=y_type
)

# Modèle 1 : Haineux vs Non Haineux
clf_type = LogisticRegression(max_iter=1000, random_state=42)
clf_type.fit(X_train, y_train_type)
y_pred_type = clf_type.predict(X_test)

print("CLASSIFICATION BINAIRE : Haineux vs Non Haineux")
print(classification_report(y_test_type, y_pred_type))

# Modèle 2 : Les 6 catégories + Non Haineux
clf_cat = LogisticRegression(max_iter=1000, random_state=42)
clf_cat.fit(X_train, y_train_cat)
y_pred_cat = clf_cat.predict(X_test)

print("CLASSIFICATION MULTICLASSE : Catégories de harcèlement")
print(classification_report(y_test_cat, y_pred_cat))

# Top 10 mots les plus importants par catégorie
feature_names = vectorizer.get_feature_names_out()
print("TOP 10 MOTS PAR CATEGORIE")
for label in clf_cat.classes_:
    idx = list(clf_cat.classes_).index(label)
    top_indices = np.argsort(clf_cat.coef_[idx])[-10:][::-1]
    top_words = [feature_names[i] for i in top_indices]
    print(f"{label:15s} : {', '.join(top_words)}")

# Export des résultats
results = pd.DataFrame({
    'Texte': df['Texte'].iloc[y_test_type.index].values,
    'Type_Réel': y_test_type.values,
    'Type_Prédit': y_pred_type,
    'Categorie_Réelle': y_test_cat.values,
    'Categorie_Prédite': y_pred_cat
})
results.to_csv('Resultats_TFIDF.csv', index=False, encoding='utf-8-sig')
print("Fichier exporté !")